package application;

public enum Views {
	MAINMENU(),
	NEWGAME(),
	BEGINNING(), CHCREATION, CHANGECHPICTURE, CLOSECHANGECHPICTURE, VILLAGE, SKILLS, DUNGEON, CHARACTERPAGE, INVENTORY, LOADGAME;
}
